### ISSUE TITLE
Allow environment variables for Run task

### ISSUE THREAD

**Issue by hamidnazari** [hamidnazari/amibaker#29]
Sample task:

``` yaml
tasks:
  - run:
    - source: /path/to/another/local/script
      cwd: /path/to/another/remote/dir
      sudo: True
      env:
        VAR1: 'Hello'
        VAR2: 'World'
```
